name: context prac

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "context"
        env:
          COMMIT_ID: ${{ toJson(github.sha) }}
        run: echo "Commit id ==> $COMMIT_ID"
      
