name: context prac

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "context"
        env:
          COMMIT_ID: ${{ toJson(github) }}
        run: echo "Commit id ==> $COMMIT_ID"

      - name: "screats test"
        env:
          test: ${{ screats.HOST }}
        run: echo "prac host info  ==> $test"
      
